services:
  agent:
    build:
      context: .
      dockerfile: agent/Dockerfile
    depends_on:
      - orchestrator
    networks:
      - net
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    ports:
      - '8080:8080'
    networks:
      - net
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - orchestrator
    networks:
      - net

networks:
  net:
    driver: bridge
