services:
  agent:
    build:
      context: .
      dockerfile: agent/Dockerfile
    depends_on:
      - orchestrator
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    ports:
      - '8080:8080'
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - orchestrator
