services:
  agent:
    build:
      context: .
      dockerfile: agent/cmd/Dockerfile
    depends_on:
      - orchestrator
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/cmd/Dockerfile
    ports:
      - '8080:8080'
  web:
    build:
      context: .
      dockerfile: web/cmd/Dockerfile
    ports:
      - '8081:<081'
    depends_on:
      - orchestrator
