services:
  agent:
    build:
      context: .
      dockerfile: agent/Dockerfile
    depends_on:
      - orchestrator
    networks:
      - back
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    ports:
      - '8080:8080'
    networks:
      - back
      - front
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - orchestrator
    networks:
      - front

networks:
  back:
    driver: bridge
  front:
    driver: bridge
