server:
  orchestrator:
    addr: '127.0.0.1:8080'
    port: 8080
  agent:
    COMPUTING_POWER: 1
  web:
    addr: '127.0.0.1:8081'
    port: 8081
    static: 'web/static'

math:
  # TIME_ADDITION_MS: 0
  # TIME_SUBTRACTION_MS: 0
  # TIME_MULTIPLICATION_MS: 0
  # TIME_DIVISION_MS: 0
  # TIME_UNARY_MINUS_MS: 0
  # TIME_POWER_MS: 0

middleware:
  api_key_prefix: ''
  authorization: ''
  cors_allow_origin:
    - '*'

logger:
  level: 0 # 0 - дебаг. Включая его будьте готовы к обильному спаму в терминал.
  time_format: '2006-01-02 15:04:05'
  call_depth: 2
  disable_call: false
  disable_time: false
  disable_color: false
