server:
  orchestrator:
    ADDR_ORCHESTRATOR: '127.0.0.1'
    PORT_ORCHESTRATOR: 8080
  agent:
    COMPUTING_POWER: 1
    AGENT_REPEAT: 5000
    AGENT_REPEAT_ERR: 2000
  web:
    ADDR_WEB: '127.0.0.1'
    PORT_WEB: 8081
    static: 'web/static'

math:
  TIME_ADDITION_MS: 0
  TIME_SUBTRACTION_MS: 0
  TIME_MULTIPLICATION_MS: 0
  TIME_DIVISION_MS: 0
  TIME_UNARY_MINUS_MS: 0
  TIME_POWER_MS: 0

middleware:
  api_key_prefix: ''
  authorization: ''
  cors_allow_origin:
    - '*'

logger:
  level: 1 # 0 - дебаг. Включая его будьте готовы к обильному спаму в терминал.
  time_format: '2006-01-02 15:04:05'
  call_depth: 2
  disable_call: false
  disable_time: false
  disable_color: false
