server:
  orchestrator:
    port: 8080
  agent:
    COMPUTING_POWER: 4
  web:
    port: 8081
    static: 'web/static'

math:
  TIME_ADDITION_MS: 100
  TIME_SUBTRACTION_MS: 200
  TIME_MULTIPLICATION_MS: 300
  TIME_DIVISION_MS: 400
  TIME_UNARY_MINUS_MS: 500
  TIME_POWER_MS: 600

middleware:
  api_key_prefix: 'Bearer'
  authorization: 'SuperHardAuthorizationPassword777'
  cors_allow_origin:
    - 'http://localhost:8081'
    - 'http://localhost:8080'

logger:
  level: 1
  time_format: '2006-01-02 15:04:05'
  call_depth: 2
  disable_call: true
  disable_time: false
  disable_color: false
