server:
  orchestrator:
    ADDR_ORCHESTRATOR: '127.0.0.1'
    PORT_ORCHESTRATOR: 8080
  agent:
    COMPUTING_POWER: 4
    AGENT_REPEAT: 5000
    AGENT_REPEAT_ERR: 2000
  web:
    ADDR_WEB: '127.0.0.1'
    PORT_WEB: 8081
    static: 'web/static'

math:
  TIME_ADDITION_MS: 100
  TIME_SUBTRACTION_MS: 200
  TIME_MULTIPLICATION_MS: 300
  TIME_DIVISION_MS: 400
  TIME_UNARY_MINUS_MS: 500
  TIME_POWER_MS: 600

middleware:
  api_key_prefix: 'Bearer '
  authorization: 'SuperHardAuthorizationPassword777'
  cors_allow_origin:
    - '*'

logger:
  level: 1
  time_format: '2006-01-02 15:04:05'
  call_depth: 2
  disable_call: true
  disable_time: false
  disable_color: false
