server:
  orchestrator:
    port: 8080
  agent:
    port: 8081
  web:
    port: 8082
    static: 'web/static'

math:
  TIME_ADDITION_MS: 0
  TIME_SUBTRACTION_MS: 0
  TIME_MULTIPLICATION_MS: 0
  TIME_DIVISION_MS: 0
  TIME_UNARY_MINUS_MS: 0
  TIME_POWER_MS: 0

cors:
  allow_origin:
    - '*'

logger:
  level: 0
  time_format: '2006-01-02 15:04:05'
  call_depth: 2
  disable_call: false
  disable_time: false
  disable_color: false
