server:
  orchestrator:
    port: 8080
  agent:
    port: 8081
  web:
    port: 8082
    static: 'web/static'

math:
  TIME_ADDITION_MS: 1000
  TIME_SUBTRACTION_MS: 1000
  TIME_MULTIPLICATION_MS: 1000
  TIME_DIVISION_MS: 1000
  TIME_UNARY_MINUS_MS: 1000
  TIME_POWER_MS: 1000

cors:
  allow_origin:
    - 'http://localhost:8082'
    - 'http://localhost:8080'

logger:
  level: 1
  time_format: '2006-01-02 15:04:05'
  call_depth: 2
  disable_call: true
  disable_time: false
  disable_color: false
